apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "healthpredict.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "healthpredict.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "healthpredict.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "healthpredict.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "healthpredict.fullname" . }}-config
            - secretRef:
                name: {{ include "healthpredict.fullname" . }}-secrets
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 30
            periodSeconds: 20
